export const newsEntries = [
  {
    id: 'press-uganda-tv',
    title: 'NTV Uganda spotlights Skooli’s solar distribution node',
    excerpt: 'Prime-time feature covers the new Gulu fulfillment centre and its 100% renewable footprint.',
    category: 'Press',
    date: 'Oct 05, 2025',
    image: '/assets/news/ntv-spotlight.svg',
    imageAlt: 'Broadcast studio featuring Skooli team',
  },
  {
    id: 'impact-gulu-cohort',
    title: 'Lakeside cohort graduates with 92% book completion rate',
    excerpt: 'Community-led micro-fulfillment ensures girls receive textbooks and hygiene kits before term start.',
    category: 'Impact',
    date: 'Sep 18, 2025',
    image: '/assets/news/lakeside-cohort.svg',
    imageAlt: 'Students celebrating with books in hand',
  },
  {
    id: 'tech-route-ai',
    title: 'Route intelligence v3 deploys predictive dwell-time modelling',
    excerpt: 'New release reduces driver idle minutes by 23% across Kampala and Fort Portal corridors.',
    category: 'Tech',
    date: 'Aug 27, 2025',
    image: '/assets/news/route-intelligence.svg',
    imageAlt: 'Logistics dashboard showing route efficiency',
  },
  {
    id: 'press-alliance',
    title: 'World Education Forum invites Skooli to impact plenary',
    excerpt: 'Global convening recognises Skooli as a leading faith-and-tech supply chain innovator.',
    category: 'Press',
    date: 'Jul 14, 2025',
    image: '/assets/news/world-education.svg',
    imageAlt: 'Conference stage with spotlight on Skooli logo',
  },
  {
    id: 'impact-savings-circle',
    title: 'Village savings circles fund 1,200 new learner kits',
    excerpt: 'Parent microfinance cohorts leverage Skooli wallets to underwrite school essentials.',
    category: 'Impact',
    date: 'Jun 29, 2025',
    image: '/assets/news/savings-circle.svg',
    imageAlt: 'Group of parents reviewing digital wallets',
  },
]
